[options]
admin_passwd = $pbkdf2-sha512$600000$ztnbey/FWMuZcy5FiLHWGg$kWXVf5olqrqA3Obfev7yH90eK6Esxj7f6FNpRQgnEkwiZ.9HVG6n.NCGcbSxo2orRWwC8e.ACwA2WSV/aeCsXg
db_host = localhost
db_port = 5432
db_user = odoo
db_password = odoo
addons_path = c:\laragon\www\odoo-project\odoo-src\addons,c:\laragon\www\odoo-project\addons,c:\laragon\www\odoo-project\addons\web-17.0
bin_path = C:\Program Files\wkhtmltopdf\bin
